version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    restart: unless-stopped

    expose:
      - 9000

    env_file:
      - .env.prod

    depends_on:
      - db

    volumes:
      - .:/var/www/html:z

    networks:
      - laravel

  db:
    image: mysql:8
    container_name: blog-mysql
    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - laravel

  nginx:
    image: nginx:1.27
    container_name: blog-nginx
    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - .:/var/www/html:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z

    depends_on:
      - app

    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
