services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - laravel
    depends_on:
      - mysql
    command: >
        sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && php-fpm"
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db-data: 
