version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    restart: unless-stopped
    volumes:
       - ./env.prod:/var/www/html/.env

    expose:
      - 9000
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: blog-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:1.27
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:z
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,z
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
